### ISSUE TITLE
[Meetup] Oviedo, Asturias, Spain

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/Community-Team#102]
### Event Type

Meetup

### Event Name

Meetup Oviedo

### Event Tracker URL

https://central.wordcamp.org/wp-admin/post.php?post=6303123&action=edit

**Comment by maion11** [comment]
Added my notes to the meetup application tracker.

**Comment by maion11** [comment]
Also, informed about the vetting in the [community-event-supporters channel.](https://wordpress.slack.com/archives/C04L4HPFGHX/p1716206956669809)
