### ISSUE TITLE
[Meetup] Lahore, Pakistan

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/Community-Team#104]
### Event Type

Meetup

### Event Name

Meetup Lahore

### Event Tracker URL

https://central.wordcamp.org/wp-admin/post.php?post=6399442&action=edit

**Comment by chaion07** [comment]
I have left my vetting comments in the application and would recommend that the applicant joins the existing Meetup Chapter and collaborates with the Leadership Team. Thanks!

**Comment by courtney-pk** [comment]
Email sent to recommend applicant join the group and connect with the organizers.
