### ISSUE TITLE
[Meetup] Eket, Akwa Ibom State, Nigeria

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#108]
### Event Name:

Eket, Akwa Ibom State, Nigeria
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=6562884&action=edit

Found Meetup application for "Eket, Akwa Ibom State, Nigeria".

**Comment by askdesign** [comment]
Vetting completed. Needs to be reviewed by a program manager.

**Comment by courtney-pk** [comment]
Application reviewed, email sent to recommend training and orientation.
