### ISSUE TITLE
[Meetup] San Pablo, Laguna

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#115]
### Event Name:

San Pablo, Laguna
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=6685700&action=edit

Found Meetup application for "San Pablo, Laguna".

**Comment by courtney-pk** [comment]
Awaiting feedback from @onealtr on this applicant, moving this issue to “In Review”.

**Comment by onealtr** [comment]
I met her at the recent WordCamp Manila (November 2023) and at WordCamp Asia Taiwan (March 2024), she is active in the WP Manila meetups but she lives 117km (72 miles) away which is a 4 hour drive. 
The San Pablo, Laguna meetup group is 50km (31 miles) from Quezon and they are willing to help out with attendees. 
The San Pablo meetup group is 68 km (42 miles) away from Manila but some members still go to Manila to attend the Manila meetup. 
I recommend this Meetup be approved and the meetup groups in San Pablo and Manila can assist in promoting and getting attendees

**Comment by courtney-pk** [comment]
Approved, sent email to arrange orientation.
