### ISSUE TITLE
[Meetup] Indore, Madhya Pradesh, India

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#127]
### Event Name:

Indore, Madhya Pradesh, India
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=6814373&action=edit

Found Meetup application for "Indore, Madhya Pradesh, India".

**Comment by courtney-pk** [comment]
@bombaypirate Note that there is a new applicant for Indore in issue #142

**Comment by bombaypirate** [comment]
Added Vetting Notes in Application
