### ISSUE TITLE
[WordCamp] Pune, India

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/Community-Team#135]
### Event Type

WordCamp

### Event Name

WordCamp Pune

### Event Tracker URL

https://central.wordcamp.org/wp-admin/post.php?post=6868108&action=edit

**Comment by yoga1103** [comment]
Hi @devinmaeztri , this is a copy of https://github.com/WordPress/Community-Team/issues/134
I had already created that issue. I've vetted it and moved the application to 'Needs Orientation/Interview'. I've marked that issue as 'Complete'.

**Comment by yoga1103** [comment]
I have closed issue #134

**Comment by kafleg** [comment]
Is this can be closed? @devinmaeztri
