### ISSUE TITLE
[WordCamp] Hoshangabad, India

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/Community-Team#137]
### Event Type

WordCamp

### Event Name

WordCamp Hoshangabad

### Event Tracker URL

https://central.wordcamp.org/wp-admin/post.php?post=6880167&action=edit

**Comment by kafleg** [comment]
Is there any update on this?

**Comment by felipevelzani** [comment]
Hey @webtechpooja, I see you reviewed this application, in case you would like to close the issue.
