### ISSUE TITLE
Thumbnail-a-thon: Let's make graphics together for the new Learn.WordPress.org!

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/Community-Team#139]
### Content Details
- **Suggested headline for the newsletter segment:** 

Introducing the first Training team Thumbnail-a-thon: Let's make graphics together for the new Learn.WordPress.org!

- **Summary of suggested content:**

Now is your chance to contribute to the new [Learn.WordPress.org ](http://learn.wordpress.org/)redesign! The official WordPress education site is launching soon with a fresh look and Learning Pathways geared to users, designers, developers, and contributors. We need help to create small thumbnail graphics for lessons and tutorials on the new site. You can see examples of what the graphics look like in the Featured Courses and Courses sections [on the new site, which can be previewed here](https://learn.wordpress.org/?new-theme=1). No previous graphics experience is required, since there's a handy tool that makes the process of creating thumbnails simple! Join us for a free [online workshop](https://www.meetup.com/learn-wordpress-online-workshops/events/301712533/) and learn how to use the tool, help us make graphics for the new site, and have some fun along the way. You'll get recognition for your contribution and get a foot in the door on the WordPress.org Training team. Everyone is welcome!

- **Share any relevant links here, including to images:**

https://www.meetup.com/learn-wordpress-online-workshops/events/301712533/
<img width="1280" alt="thumbnail-workshop" src="https://github.com/WordPress/Community-Team/assets/7662449/bf5e3bfa-9dff-4022-abc5-c1eb2ba58c0c">

- **During which month should this be published?**

Before June 25, 2024. If the newsletter will only be sent out after that date, I will add a link to the recording if you'd like to share that instead, modifying the above wording accordingly.

- **Why is this content timely and relevant?**

Learn.WordPress.org is relaunching soon and having all hands on deck will help make the site look the best it can!

### Additional Information
- **Target Audience:**
  - [ ] New organizers
  - [ ] Experienced organizers
  - [x] General community

- **Permission to Edit:**
  - [x] I allow the editorial team to make necessary edits.

**Comment by hellojuliarose** [comment]
This has been published: https://make.wordpress.org/community/2024/06/24/meetup-organizer-newsletter-june-2024/

**Comment by peiraisotta** [comment]
@hellojuliarose can we close this issue if the content was included in the newsletter already? Thank you!
