### ISSUE TITLE
[Meetup] Indore, Madhya Pradesh, India

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#142]
### Event Name:

Indore, Madhya Pradesh, India
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=6873209&action=edit

Found Meetup application for "Indore, Madhya Pradesh, India".

**Comment by courtney-pk** [comment]
This is a new applicant for Indore. Note that there is another applicant in issue #127

**Comment by bombaypirate** [comment]
Changes Requested -  Vetting Notes added.
