### ISSUE TITLE
[Meetup] Tonawanda, NY, US

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#143]
### Event Name:

Tonawanda, NY, US
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=6881094&action=edit

Found Meetup application for "Tonawanda, NY, US".

**Comment by askdesign** [comment]
Vetting completed. 
NEXT STEPS: This application needs a program manager's eyes and feedback for me as to what I should do next.

**Comment by courtney-pk** [comment]
I have added my notes to the tracker. Thank you!

**Comment by askdesign** [comment]
I wrote an email to Josh with our recommendations. I copied 2 of the co-organizers on my reply and separately reached out to them on Meetup.com.

**Comment by devinmaeztri** [comment]
Hello, @askdesign! Could you please this ticket, so it appears on your WP.org profile? Thank you :)
