### ISSUE TITLE
[Meetup] Tunis

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#145]
### Event Name:

Tunis
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=6892210&action=edit

Found Meetup application for "Tunis".

**Comment by peiraisotta** [comment]
Needs second opinion.

**Comment by courtney-pk** [comment]
Added additional notes to tracker.

**Comment by peiraisotta** [comment]
Thank you for the feedback. I was able to move this application forward.Thank you for the feedback. I was able to move this application forward.
