### ISSUE TITLE
Sustainable Events Handbook

### ISSUE THREAD

**Issue by peiraisotta** [WordPress/Community-Team#146]
### Content Details
- **Suggested headline for the newsletter segment:** 
- Sustainable Events Handbook

- **Summary of suggested content:**
The sustainability team published the Sustainable Events Handbook and I think that we should amplify it https://make.wordpress.org/sustainability/handbook/sustainable-events/

- **Full content (if applicable):**

- **Share any relevant links here, including to images:**

- **How does this content inform, empower, or inspire meetup organizers?**
- A guide to organize more sustainable events

- **During which month should this be published?**
- July or August

- **Why is this content timely and relevant?**
- Becasue it would impact all future events

### Additional Information
- **Target Audience:**
  - [ ] New organizers
  - [ ] Experienced organizers
  - [X] General community

- **Any Additional Notes or Comments:**

- **Permission to Edit:**
  - [x] I allow the editorial team to make necessary edits.

**Comment by hellojuliarose** [comment]
I plan to include this brief article in the June Meetup Organizer Newsletter, which we aim to publish on Monday, June 24. How does this look to you?

### Announcing the New Handbook for Sustainable WordPress Events
Are you interested in how your Meetup group can be more sustainable? Check out the brand new [Sustainability Handbook](https://make.wordpress.org/sustainability/handbook/sustainable-events/), created by the [WordPress Sustainability Team](https://make.wordpress.org/sustainability/handbook/contribute/).

**Comment by peiraisotta** [comment]
This would be great. Thank you so much, @hellojuliarose !

**Comment by hellojuliarose** [comment]
This has been published: https://make.wordpress.org/community/2024/06/24/meetup-organizer-newsletter-june-2024/
