### ISSUE TITLE
[Meetup] Tulsa, Oklahoma

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#149]
### Event Name:

Tulsa, Oklahoma
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=6918646&action=edit

Found Meetup application for "Tulsa, Oklahoma".

**Comment by askdesign** [comment]
I have completed the vetting. It now needs to be reviewed by a program manager.

**Comment by courtney-pk** [comment]
I have reviewed and added notes to the tracker as well.

**Comment by courtney-pk** [comment]
Email sent to recommend training and orientation.

**Comment by askdesign** [comment]
Thank you, @courtney-pk . I've changed the status of this issue to Complete.
