### ISSUE TITLE
[WordCamp] Kolhapur, India

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/Community-Team#150]
### Event Type

WordCamp

### Event Name

WordCamp Kolhapur

### Event Tracker URL
https://central.wordcamp.org/wp-admin/post.php?post=6919111&action=edit

WordCamp Kolhapur, Maharashtra, India

**Comment by webtechpooja** [comment]
I have reviewed this application and updated the notes in the tracker. Orientation email sent to the applicant.
