### ISSUE TITLE
[Meetup] Shanghai, China

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#153]
### Event Name:

Shanghai, China
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=6936254&action=edit

Found Meetup application for "Shanghai, China".

**Comment by dorsvenabili** [comment]
I've updated the WC tracker and I'm waiting for more info from @nukaga and @onealtr. We'll update this ticket asap.

**Comment by onealtr** [comment]
hello, I've vetted the organizers of this WC, and then @devinmaeztri did another pass vetting and spoke with them for orientation. there were some concerns about their site's GPL compliance which they said they would change.

**Comment by kafleg** [comment]
Vetting completed. 

Thank you
