### ISSUE TITLE
[Meetup] Bekasi. Indonesia

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#157]
### Event Name:

Bekasi
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7048755&action=edit

Found Meetup application for "Bekasi".

**Comment by devinmaeztri** [comment]
I'll review the application as part of the July reactivation initiative.

**Comment by devinmaeztri** [comment]
Application is vetted and follow-up email is sent.
