### ISSUE TITLE
Team Meeting Host - November session #2

### ISSUE THREAD

**Issue by peiraisotta** [WordPress/Community-Team#176]

**Comment by peiraisotta** [comment]
Script: https://docs.google.com/document/d/1BnvIVXIP_Vmv6CZttmtyIfOSETg-8sQJfNrrfS-zRsc/edit?usp=sharing

**Comment by alexcu21** [comment]
@peiraisotta please reasign this to @zinanga he is the actual host for today meeting.

**Comment by peiraisotta** [comment]
Done! Thank you both @alexcu21 and @zinanga
