### ISSUE TITLE
[Meetup] Guwahati, Assam, India

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#188]
### Event Name:

Guwahati, Assam, India
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7095574&action=edit

Found Meetup application for "Guwahati, Assam, India".

**Comment by webtechpooja** [comment]
Email sent for asking more information, Once we get more information, we can proceed it further.
