### ISSUE TITLE
[Meetup] Kabupaten Bekasi, Jawa Barat, Indonesia (Bekasi Meetup)

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#191]
### Event Name:

Kabupaten Bekasi, Jawa Barat, Indonesia (Bekasi Meetup)
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7146052&action=edit

Found Meetup application for "Kabupaten Bekasi, Jawa Barat, Indonesia (Bekasi Meetup)".

**Comment by devinmaeztri** [comment]
I have reviewed the application and sent a follow-up email.
