### ISSUE TITLE
[Meetup] Mbarara, Western, Uganda

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#195]
### Event Name:

Mbarara, Western, Uganda
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7157172&action=edit

Found Meetup application for "Mbarara, Western, Uganda".

**Comment by askdesign** [comment]
Vetting completed. Needs to be reviewed by community program support manager.

**Comment by courtney-pk** [comment]
Reviewed and have no additional notes. OK to recommend training and orientation.

**Comment by askdesign** [comment]
Email sent recommending training and orientation.
