### ISSUE TITLE
[Meetup] Alicante, Spain

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#203]
### Event Name:

Alicante, Spain
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7169708&action=edit

Found Meetup application for "Alicante, Spain".

**Comment by lumicliment** [comment]
Reviewed and closed

**Comment by devinmaeztri** [comment]
Hello, @lumicliment! The event application is still listed as needs vetting and there is no updated notes. Could you please help reconfirm. Thank you! 

https://central.wordcamp.org/wp-admin/post.php?post=7169708&action=edit

**Comment by flopez1977** [comment]
this application was opened and waiting for vetting, I close it
