### ISSUE TITLE
[Meetup] Collado Villalba

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#207]
### Event Name:

Collado Villalba
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7170638&action=edit

Found Meetup application for "Collado Villalba".

**Comment by flopez1977** [comment]
vetting done and change to otientation/ionterview to active the meetup

**Comment by devinmaeztri** [comment]
Hello, @flopez1977! Please close the issue so it will appear on your WordPress.org profile. Thank you! :)
