### ISSUE TITLE
[Meetup] Montpellier, France

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#222]
### Event Name:

Montpellier, France
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7214216&action=edit

Found Meetup application for "Montpellier, France".

**Comment by devinmaeztri** [comment]
Hello, @peiraisotta! Could you please close this ticket, so it appears on your WP.org profile? Thank you :)

**Comment by peiraisotta** [comment]
Sure, thank you, @devinmaeztri !
