### ISSUE TITLE
[Meetup] Arnhem or Ede

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#223]
### Event Name:

Arnhem or Ede (last one better)
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7215143&action=edit

Found Meetup application for "Arnhem or Ede (last one better)".

**Comment by devinmaeztri** [comment]
Application is reviewed and follow-up email has been sent.
