### ISSUE TITLE
[Meetup] AGRA, UTTAR PRADESH, INDIA

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#231]
### Event Name:

AGRA, UTTAR PRADESH, INDIA
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7261016&action=edit

Found Meetup application for "AGRA, UTTAR PRADESH, INDIA".

**Comment by devinmaeztri** [comment]
Application reviewed and follow-up email sent.
