### ISSUE TITLE
[Meetup] Ibadan, Oyo State, Nigeria

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#251]
### Event Name:

Ibadan, Oyo State, Nigeria
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7364773&action=edit

Found Meetup application for "Ibadan, Oyo State, Nigeria".

**Comment by devinmaeztri** [comment]
The application is reviewed and followed up.
