### ISSUE TITLE
[Meetup] Cape Town

### ISSUE THREAD

**Issue by hellojuliarose** [WordPress/Community-Team#259]
### Event Name:

Cape Town
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7449547&action=edit

Found Meetup application for "Cape Town".

**Comment by flopez1977** [comment]
#### 5th Sept 2024 ####
There is currently an active meetup group: https://central.wordcamp.org/wp-admin/post.php?post=3164285&action=edit a reply has been sent to the applicant to contact the organiser to collaborate with them.
