### ISSUE TITLE
[Meetup] Tokushima, Japan

### ISSUE THREAD

**Issue by naokomc** [WordPress/Community-Team#262]
### Event Name:
Tokushima, Japan

### Event Type:
Meetup

### Tracker URL:
https://central.wordcamp.org/wp-admin/post.php?post=7466694&action=edit

Found Meetup application for "Tokushima, Japan".

**Comment by nukaga** [comment]
The applicant was already a co-organizer of the Tokushima WordPressMeetup. The application was filed under a misunderstanding.
