### ISSUE TITLE
[Meetup] Port Elizabeth/Gqberha

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#265]
### Event Name:

Port Elizabeth/Gqberha
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7451409&action=edit

Found Meetup application for "Port Elizabeth/Gqberha".

**Comment by flopez1977** [comment]
Vetted done, send welcome mail to make the orientation
