### ISSUE TITLE
[Meetup] Masvingo, Masvingo Province, Zimbabwe

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#268]
### Event Name:

Masvingo, Masvingo Province, Zimbabwe
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7489846&action=edit

Found Meetup application for "Masvingo, Masvingo Province, Zimbabwe".

**Comment by flopez1977** [comment]
Requested to do a meetuo organiser training course prior to an interview.
