### ISSUE TITLE
[Meetup] Gangtok, Sikkim

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#269]
### Event Name:

Gangtok, Sikkim
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7494009&action=edit

Found Meetup application for "Gangtok, Sikkim".

**Comment by kafleg** [comment]
@devinmaeztri we need to approve this meetup as I talked with organizer in chat and he is interested to do meetup soon.

**Comment by kafleg** [comment]
Vetting completed. 

Thank you
