### ISSUE TITLE
[Meetup] Durban, Kwa-Zulu Natal, South Africa

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#271]
### Event Name:

Durban, Kwa-Zulu Natal, South Africa
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7515750&action=edit

Found Meetup application for "Durban, Kwa-Zulu Natal, South Africa".

**Comment by flopez1977** [comment]
email sent
