### ISSUE TITLE
[Meetup] Iligan City, Northern Mindanao, Philippines

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#274]
### Event Name:

Iligan City, Northern Mindanao, Philippines
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7597888&action=edit

Found Meetup application for "Iligan City, Northern Mindanao, Philippines".

**Comment by flopez1977** [comment]
Email for interview and orientation sent.
