### ISSUE TITLE
[Meetup] Florianópolis

### ISSUE THREAD

**Issue by peiraisotta** [WordPress/Community-Team#276]
### Event Name:

Florianópolis
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7609705&action=edit

Found Meetup application for "Florianópolis".

**Comment by flopez1977** [comment]
Already a meetup in this area: https://www.meetup.com/es-ES/meetup-wordpress-floripa/
Contacto organizador: [contato@incuca.com.br](mailto:contato@incuca.com.br)
