### ISSUE TITLE
[Meetup] Puerto Ordaz, Bolívar, Venezuela

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#279]
### Event Name:

Puerto Ordaz, Bolívar, Venezuela
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7623147&action=edit

Found Meetup application for "Puerto Ordaz, Bolívar, Venezuela".

**Comment by flopez1977** [comment]
Vetted and send mail for interview
