### ISSUE TITLE
[Meetup] Kalika, Chitwan, Nepal

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#280]
### Event Name:

Kalika, Chitwan, Nepal
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7672216&action=edit

Found Meetup application for "Kalika, Chitwan, Nepal".

**Comment by flopez1977** [comment]
another meetup near at 20 minutes from the city of the applicant. email sent
