### ISSUE TITLE
[Meetup] Soon Valley Naushera, District Khushab, Punjab, Pakistan

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#281]
### Event Name:

Soon Valley Naushera, District Khushab, Punjab, Pakistan
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7694444&action=edit

Found Meetup application for "Soon Valley Naushera, District Khushab, Punjab, Pakistan".

**Comment by flopez1977** [comment]
email sent for orientation
