### ISSUE TITLE
[Meetup] Pereira - Risaralda - Colombia

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#284]
### Event Name:

Pereira - Risaralda - Colombia
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7724129&action=edit

Found Meetup application for "Pereira – Risaralda – Colombia".

**Comment by flopez1977** [comment]
Sent mail for orientations
