### ISSUE TITLE
[WordCamp] Brisbane, Australia

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/Community-Team#289]
### Event Type

WordCamp

### Event Name

WordCamp Brisbane 

### Event Tracker URL

https://central.wordcamp.org/wp-admin/post.php?post=7817646&action=edit

**Comment by huanyichuang** [comment]
@devinmaeztri no red flags, the applicant is active and is also part of the WordCamp Sydney organizers. I've also sent the email to the person with the safe reply template.
