### ISSUE TITLE
[WordCamp] Kathmandu, Nepal

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/Community-Team#290]
### Event Type

WordCamp

### Event Name

WordCamp Kathmandu

### Event Tracker URL

https://central.wordcamp.org/wp-admin/post.php?post=7817649&action=edit

**Comment by webtechpooja** [comment]
I am vetting WOrdCamp Kathmandu, Nepal

**Comment by webtechpooja** [comment]
I have vetted the application, moved it to the status of more info requested, and also written my findings in the comment.

**Comment by webtechpooja** [comment]
Email sent to schedule orientation call.
