### ISSUE TITLE
[WordCamp] Buffalo, NY, USA

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/Community-Team#295]
### Event Type

WordCamp

### Event Name

WordCamp Buffalo

### Event Tracker URL

https://central.wordcamp.org/wp-admin/post.php?post=7854690&action=edit

**Comment by kcristiano** [comment]
Reviewed app , set to needs orientation and added comments.

**Comment by devinmaeztri** [comment]
The follow-up email has been sent.
