### ISSUE TITLE
[Meetup] Dinajpur, Bangladesh

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/Community-Team#309]
### Event Type

Meetup

### Event Name

Meetup Dinajpur

### Event Tracker URL

https://central.wordcamp.org/wp-admin/post.php?post=8044103&action=edit

**Comment by kafleg** [comment]
Vetting Done.

**Comment by devinmaeztri** [comment]
Hi @flopez1977, if you have sent the follow-up email, could you please ping @kafleg. So he can close this ticket. Thanks so much, Fernando and Ganga!

**Comment by kafleg** [comment]
Email sent.
