### ISSUE TITLE
[Meetup] Istanbul, Turkey 

### ISSUE THREAD

**Issue by flopez1977** [WordPress/Community-Team#317]
Event Name:
Istanbul

Event Type:
Meetup

Tracker URL:
Central tracker: https://central.wordcamp.org/wp-admin/post.php?post=8209351&action=edit

**Comment by maion11** [comment]
The application has been vetted.

**Comment by webtechpooja** [comment]
I sent an email requesting more information; let's wait a few days for their reply!
