### ISSUE TITLE
[WordCamp] WordPress Youth Day, San José, Costa Rica

### ISSUE THREAD

**Issue by bombaypirate** [WordPress/Community-Team#318]
### Event Name:

WordCamp WordPress Youth Day, San José, Costa Rica
### Event Type:

WordCamp
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=8239503&action=edit

Found WordCamp application for "WordCamp WordPress Youth Day, San José, Costa Rica".

**Comment by felipevelzani** [comment]
(I am unassigning myself as I ended up with a lot of tasks and couldn't look into it yet, but I might be able to work on some reviews if we don't have someone to check them by the end of the week.)
