### ISSUE TITLE
[WordCamp] Iskandar Puteri / Johor Bahru, Johor, Malaysia

### ISSUE THREAD

**Issue by bombaypirate** [WordPress/Community-Team#322]
### Event Name:

WordCamp Iskandar Puteri / Johor Bahru, Johor, Malaysia
### Event Type:

WordCamp
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=8262696&action=edit

Found WordCamp application for "WordCamp Iskandar Puteri / Johor Bahru, Johor, Malaysia".

**Comment by onealtr** [comment]
application vetted, notes here: https://central.wordcamp.org/wp-admin/post.php?post=8262696&action=edit

**Comment by muddassirnasim** [comment]
Changed name to WordCamp Johor Bahru
