### ISSUE TITLE
[Meetup] Istanbul

### ISSUE THREAD

**Issue by felipevelzani** [WordPress/Community-Team#325]
### Event Name:

Istanbul
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=8209351&action=edit

Found Meetup application for "Istanbul".

**Comment by devinmaeztri** [comment]
Hello, @foosantos, since @flopez1977 has created a ticket before this one, should we merge them? 
https://github.com/WordPress/Community-Team/issues/317

**Comment by devinmaeztri** [comment]
Hello, @maion11. If you know how to merge two tickets, could you please help merge this one with the one assigned to you? Thanks a lot!

**Comment by maion11** [comment]
Hi @devinmaeztri , done!
