### ISSUE TITLE
[WordCamp] Jinja, Uganda

### ISSUE THREAD

**Issue by felipevelzani** [WordPress/Community-Team#328]
### Event Name:

Jinja, Uganda
### Event Type:

WordCamp
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=8232077&action=edit

Found WordCamp application for "Jinja, Uganda".

**Comment by nukaga** [comment]
I'll close this as it seems to be a duplicate of [WordCamp] Jinja, Uganda #320
