### ISSUE TITLE
[Meetup] Colombo, Sri Lanka

### ISSUE THREAD

**Issue by felipevelzani** [WordPress/Community-Team#330]
### Event Name:

Colombo, Sri Lanka
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=8233476&action=edit

Found Meetup application for "Colombo, Sri Lanka".

**Comment by maion11** [comment]
The application has been vetted.

**Comment by webtechpooja** [comment]
I have sent an email and asked the applicant to do a meetup organizer training. Once they will complete and get back to us, we can proceed with the orienatation.
