### ISSUE TITLE
[WordPress Event] San José, Costa Rica

### ISSUE THREAD

**Issue by nukaga** [WordPress/Community-Team#336]
### Event Name:

Women WordPress Day 2025, San José, Costa Rica
### Event Type:

WordPress Event
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=8271503&action=edit

Found WordCamp application for "Women WordPress Day 2025, San José, Costa Rica".

**Comment by lidarroy** [comment]
Enviado correo para orientación
