### ISSUE TITLE
[Meetup] Jhenaidah Sadar, Khulna, Bangladesh

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/Community-Team#341]
### Event Type

Meetup

### Event Name

Meetup Jhenaidah Sadar

### Event Tracker URL

https://central.wordcamp.org/wp-admin/post.php?post=8363672&action=edit

**Comment by maion11** [comment]
The application has been vetted.

**Comment by webtechpooja** [comment]
Email Sent to schedule an orientation call
