### ISSUE TITLE
[WordCamp] WordCamp Kraków, Poland

### ISSUE THREAD

**Issue by nukaga** [WordPress/Community-Team#349]
### Event Name:

WordCamp Kraków, Poland
### Event Type:

WordCamp
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=8422107&action=edit

Found WordCamp application for "WordCamp Kraków, Poland".

**Comment by felipevelzani** [comment]
Hey @dorsvenabili, FYI, you missed marking it as closed here, so I'm letting you do it so it reflects on your stats/profile. :)
