### ISSUE TITLE
[Meetup] Bình thạnh Hồ Chí Minh

### ISSUE THREAD

**Issue by nukaga** [WordPress/Community-Team#350]
### Event Name:

Bình thạnh Hồ Chí Minh
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=8430909&action=edit

Found Meetup application for "Bình thạnh Hồ Chí Minh".

**Comment by bombaypirate** [comment]
Vetting complete - Email sent.
