### ISSUE TITLE
[Meetup] Zaprešić 10290, Croatia

### ISSUE THREAD

**Issue by nukaga** [WordPress/Community-Team#352]
### Event Name:

Zaprešić 10290, Croatia
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=8451300&action=edit

Found Meetup application for "Zaprešić 10290, Croatia".

**Comment by flopez1977** [comment]
Email sent asking more info. Is not clear what she needs.

**Comment by flopez1977** [comment]
the application is closed
