### ISSUE TITLE
[Meetup] Gbagada, Lagos, Nigeria

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/Community-Team#357]
### Event Type

Meetup

### Event Name

Gbagada, Lagos, Nigeria

### Event Tracker URL

https://central.wordcamp.org/wp-admin/post.php?post=8536607&action=edit

**Comment by jovialcore** [comment]
Hi, Nigerian here 👋 . Do you mind if I get more information or any pointers as to how I would go about this. Sounds interesting I could take it up. Thank you.

**Comment by felipevelzani** [comment]
Hi @jovialcore! Thank you so much for your interest to contribute. Can you share more about your interest and how you would like to get involved?

You can join us on Slack here and can talk more from there: https://make.wordpress.org/chat/

**Comment by felipevelzani** [comment]
As a side note, I already reviewed this specific case, and I'm closing it here.
