### ISSUE TITLE
[Meetup] Sta. Rosa, Laguna, Philippines

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/Community-Team#367]
### Event Type

Meetup

### Event Name

Meetup Sta. Rosa

### Event Tracker URL

https://central.wordcamp.org/wp-admin/post.php?post=8565415&action=edit

**Comment by khleomix** [comment]
@devinmaeztri I’ve added my findings to both the tracker and HelpScout so everything is documented and easy to access later.
