### ISSUE TITLE
[Meetup] Yerevan, Armenia

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/Community-Team#368]
### Event Type

Meetup

### Event Name

Meetup Yerevan

### Event Tracker URL

Yerevan, Armenia

**Comment by felipevelzani** [comment]
Maybe you can try this one @mauteri next week if possible. 

Edit: I might actually review this one still this week, but I appreciate if you can look at [any pending on next week](https://github.com/WordPress/Community-Team/issues?q=is%3Aissue%20state%3Aopen%20label%3Aapplication%20no%3Aassignee%20%20sort%3Acreated-asc).

**Comment by yoga1103** [comment]
Application moved to 'Needs Orientation'
