### ISSUE TITLE
[WordPress Event] Managua, Nicaragua

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/Community-Team#370]
### Event Type

WordPress Event

### Event Name

Woman WordPress Day Nicaragua

### Event Tracker URL

https://central.wordcamp.org/wp-admin/post.php?post=8577930&action=edit

**Comment by khleomix** [comment]
@devinmaeztri Application has been vetted and tracker updated. I've sent the group orientation email in HelpScout.
