### ISSUE TITLE
[Meetup] Straßwalchen, Salzburg

### ISSUE THREAD

**Issue by wpcommunityteam** [WordPress/Community-Team#374]
### Event Name:

Straßwalchen, Salzburg

### Event Type:

Meetup

### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=8643442&action=edit

### Help Scout conversation:

https://secure.helpscout.net/conversation/2769716036/674366

**Comment by kafleg** [comment]
I did the vetting for this application.
