### ISSUE TITLE
[Meetup] Ipoh / Perak

### ISSUE THREAD

**Issue by wpcommunityteam** [WordPress/Community-Team#375]
### Event Name:

Ipoh / Perak

### Event Type:

Meetup

### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=8656878&action=edit

### Help Scout conversation:

https://secure.helpscout.net/conversation/2771068611/675213

**Comment by kafleg** [comment]
Vetting done! 

Thank you
