### ISSUE TITLE
[Meetup] BSB, Brunei Darussalam

### ISSUE THREAD

**Issue by wpcommunityteam** [WordPress/Community-Team#376]
### Event Name:

BSB, Brunei Darussalam

### Event Type:

Meetup

### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=8687493&action=edit

### Help Scout conversation:

https://secure.helpscout.net/conversation/2772945194/676107

**Comment by maion11** [comment]
The application has been vetted.

**Comment by maion11** [comment]
Hi @webtechpooja , I have completed the vetting. Can you send them an email?
Thanks

**Comment by webtechpooja** [comment]
As suggested, an email has been sent to complete the Meetup organizer training first, then schedule an orientation call.
