### ISSUE TITLE
[WordCamp] Zaragoza

### ISSUE THREAD

**Issue by wpcommunityteam** [WordPress/Community-Team#380]
### Event Name:

Zaragoza

### Event Type:

WordCamp

### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=8706525&action=edit

### Help Scout conversation:

https://secure.helpscout.net/conversation/2775049816/677107

**Comment by lidarroy** [comment]
Vetting ready, orientation mail sent.
