### ISSUE TITLE
[Meetup] Móstoles, Madrid - Spain

### ISSUE THREAD

**Issue by wpcommunityteam** [WordPress/Community-Team#381]
### Event Name:

Móstoles, Madrid - Spain

### Event Type:

Meetup

### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=8711627&action=edit

### Help Scout conversation:

https://secure.helpscout.net/conversation/2775424085/677393

**Comment by flopez1977** [comment]
already vetted and mail sent
