### ISSUE TITLE
[Meetup] Varanasi, In

### ISSUE THREAD

**Issue by wpcommunityteam** [WordPress/Community-Team#387]
### Event Name:

Varanasi, In

### Event Type:

Meetup

### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=8775583&action=edit

### Help Scout conversation:

https://secure.helpscout.net/conversation/2780616509/679988

**Comment by kafleg** [comment]
Vetting done. Request @flopez1977 to send an email to the organizer.
