### ISSUE TITLE
[Meetup] Accra, Ghana

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Community-Team#39]
### Event Name:

Accra, Ghana
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=5724295&action=edit

Found Meetup application for "Accra, Ghana".

**Comment by courtney-pk** [comment]
This application was processed [in issue #91](https://github.com/WordPress/Community-Issue-Tracker/issues/91). How should we proceed with this one?

**Comment by courtney-pk** [comment]
This was vetted using a duplicate issue, so I'm moving my notes here.

Vetted on 8 March 2024:
Added my vetting notes to the Tracker and sent email to applicant to schedule orientation.
