### ISSUE TITLE
[Meetup] Ikot Ekpene/ Akwa Ibom State

### ISSUE THREAD

**Issue by wpcommunityteam** [WordPress/Community-Team#398]
### Event Name:

Ikot Ekpene/ Akwa Ibom State

### Event Type:

Meetup

### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=8849364&action=edit

### Help Scout conversation:

https://secure.helpscout.net/conversation/2787261089/683184

**Comment by kafleg** [comment]
Done vetting.
