### ISSUE TITLE
[Meetup] Shillong

### ISSUE THREAD

**Issue by peiraisotta** [WordPress/Community-Team#40]
### Event Name:

Shillong
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=5756386&action=edit

### Helpscout URL:
https://secure.helpscout.net/conversation/2532763642/174276/

Found Meetup application for "Shillong".

**Comment by webtechpooja** [comment]
I have added notes to the tracker and onboarding email sent to the applicant.
