### ISSUE TITLE
[WordCamp] WordCamp Buea, South West Region, Cameroon

### ISSUE THREAD

**Issue by leogopal** [WordPress/Community-Team#404]
### Event Name:
 WordCamp Buea, South West Region, Cameroon
### Event Type:
 WordCamp
  ### Tracker URL:
 https://central.wordcamp.org/wp-admin/post.php?post=8849362&action=edit

Found WordCamp application for "WordCamp Buea, South West Region, Cameroon".

**Comment by felipevelzani** [comment]
Hey @leogopal, I'm closing this issue as it is duplicated from https://github.com/WordPress/Community-Team/issues/397. Btw, the issues are created automatically now, so you don't need to create them manually.
