### ISSUE TITLE
[WordCamp] WordCamp Netherlands

### ISSUE THREAD

**Issue by hellojuliarose** [WordPress/Community-Team#50]
### Event Name: WordCamp Netherlands

WordCamp Netherlands
### Event Type: WordCamp

WordCamp
### Tracker URL: https://central.wordcamp.org/wp-admin/post.php?post=5927253&action=edit

Found WordCamp application for "WordCamp Netherlands".

**Comment by webtechpooja** [comment]
Another application has been submitted; https://github.com/WordPress/Community-Team/issues/92
this application has been canceled. so closing the issue .
