### ISSUE TITLE
[Meetup] Shenzhen, Guangdong, China

### ISSUE THREAD

**Issue by onealtr** [WordPress/Community-Team#51]
### Event Name:

Shenzhen, Guangdong, China
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=5914277&action=edit

Found Meetup application for "Shenzhen, Guangdong, China".

**Comment by leogopal** [comment]
Thanks @onealtr -- all looks good, please close this issue to have it logged on your WP.org profile.
