### ISSUE TITLE
[WordCamp] WordCamp Philadelphia

### ISSUE THREAD

**Issue by hellojuliarose** [WordPress/Community-Team#55]
### Event Name:

WordCamp Philadelphia
### Event Type:

WordCamp
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=5986983&action=edit

Found WordCamp application for "WordCamp Philadelphia".

**Comment by devinmaeztri** [comment]
Hello, @hellojuliarose, since you vetted the application and the application has been followed up. Could you please help close the issue? Thank you!

**Comment by bombaypirate** [comment]
Hello, @hellojuliarose, moving the ticket to COmplete does not close it. And closing the ticket will then show it attributed to your WP.org Profile. You can close the ticket simply from the comments.
I have added an image to help better.

![Image](https://github.com/WordPress/Community-Team/assets/5043776/1db93268-8333-4d7b-82a7-883432703e49)
