### ISSUE TITLE
[Meetup] Strasbourg, France

### ISSUE THREAD

**Issue by bombaypirate** [WordPress/Community-Team#58]
### Event Name:

Strasbourg, France
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=6012061&action=edit

Found Meetup application for "Strasbourg, France".

**Comment by courtney-pk** [comment]
Added my vetting notes to the Tracker and sent email to applicant to schedule orientation.

**Comment by bombaypirate** [comment]
@courtney-pk Can you close this ticket. Basically Click Close with Comment here and the issue is closed in your name.
