### ISSUE TITLE
[Meetup] Aquitaine (Bordeaux)

### ISSUE THREAD

**Issue by bombaypirate** [WordPress/Community-Team#59]
### Event Name:

Aquitaine
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=5981887&action=edit

Found Meetup application for "Aquitaine".

**Comment by courtney-pk** [comment]
Note that this Meetup group is in Bordeaux. Changed the name of the city in the Tracker from Aquitaine to Bordeaux.

Vetting notes added to the tracker, email sent to applicant to schedule orientation.
