### ISSUE TITLE
[Meetup] Lehi, Utah

### ISSUE THREAD

**Issue by bombaypirate** [WordPress/Community-Team#61]
### Event Name:

Lehi, Utah
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=5915204&action=edit

Found Meetup application for "Lehi, Utah".

**Comment by courtney-pk** [comment]
Email sent to clarify GPL of derivatives, application on hold till we hear a response.

**Comment by courtney-pk** [comment]
No response from applicant, declining application.
