### ISSUE TITLE
[Meetup] Singapore (2nd Organiser)

### ISSUE THREAD

**Issue by bombaypirate** [WordPress/Community-Team#63]
### Event Name:

Singapore
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=6004626&action=edit

Found Meetup application for "Singapore".

**Comment by webtechpooja** [comment]
I wrote notes in Tracker, and the orientation email has been sent to the applicant. ​However, we received two applications for reactivating the Meetup group in Singapore. So, I invited both of them for an orientation call.
