### ISSUE TITLE
[WordCamp] WordCamp Miami, Florida

### ISSUE THREAD

**Issue by askdesign** [WordPress/Community-Team#65]
### Event Type

WordCamp

### Event Name

WordCamp Miami, Florida

### Event Tracker URL

https://central.wordcamp.org/wordcamps/wordcamp-miami-florida-2/

**Comment by devinmaeztri** [comment]
Hello @askdesign! Please let me know if you have any questions or need help with the reviewing process. Once you complete the review and send a follow-up email to the applicant, could you please close this issue? Thank you!

**Comment by askdesign** [comment]
hello @devinmaeztri !
Follow-up email sent to applicant requesting for more information and consistent MeetUp gatherings for at least 6 months. If/When he/they reapply, should I come back to this issue and open it?

**Comment by askdesign** [comment]
Applicant has a few things to do before we can approve the WordCamp.
