### ISSUE TITLE
[Meetup]: Orai

### ISSUE THREAD

**Issue by onealtr** [WordPress/Community-Team#68]
### Meetup City, Event Name

Orai, Uttar Pradesh, India

### Meetup Tracker Link

https://central.wordcamp.org/wp-admin/post.php?post=4962570&action=edit

### Meetup HelpScout Link

https://secure.helpscout.net/conversation/2463562117/170516/

**Comment by onealtr** [comment]
No reply via email since January 24, 2024

**Comment by onealtr** [comment]
Sent a follow up email for more information

**Comment by devinmaeztri** [comment]
Hello @onealtr! The application has been cancelled due to lack of response. Do you want to close this issue? So it appears on your profile. :)

**Comment by courtney-pk** [comment]
I am closing this issue to keep our board up to date. Thank you!
