### ISSUE TITLE
[WordCamp]: WordCamp San José, Costa Rica

### ISSUE THREAD

**Issue by bombaypirate** [WordPress/Community-Team#69]
### WordCamp City, Event Name

WordCamp San José

### WordCamp Tracker Link

https://central.wordcamp.org/wp-admin/post.php?post=5138356&action=edit

### WordCamp HelpScout Link

https://secure.helpscout.net/conversation/2478060198/171177/

**Comment by bombaypirate** [comment]
@lumicliment Can you close this ticket as you completed the vetting on this application.

**Comment by lumicliment** [comment]
@bombaypirate Thanks for the reminder.
