### ISSUE TITLE
[Meetup] Metairie

### ISSUE THREAD

**Issue by hellojuliarose** [WordPress/Community-Team#72]
### Event Name:

Metairie
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=6148351&action=edit
https://central.wordcamp.org/wp-admin/post.php?post=6207601&action=edit

Found Meetup application for "Metairie".

**Comment by devinmaeztri** [comment]
There are 2 applications from Metairie: [Metairie, Louisiana, u.S.A.](https://central.wordcamp.org/wp-admin/post.php?post=6207601&action=edit)

**Comment by courtney-pk** [comment]
Noting that the applicant submitted a second application under a different email address:
https://central.wordcamp.org/wp-admin/post.php?post=6207601&action=edit

**Comment by courtney-pk** [comment]
> There are 2 applications from Metairie: [Metairie, Louisiana, u.S.A.](https://central.wordcamp.org/wp-admin/post.php?post=6207601&action=edit)

Noting that this is the same applicant, submitted with a different email address. Applicant has no preference of email, so I will process the first submission and cancel the second.

**Comment by courtney-pk** [comment]
Reached out for more information, moved to `In Review`.

**Comment by courtney-pk** [comment]
More information received, application approved. Sent email to recommend training and orientation.
