### ISSUE TITLE
[Meetup] Asunción, Paraguay

### ISSUE THREAD

**Issue by hellojuliarose** [WordPress/Community-Team#73]
### Event Name:

Asunción, Paraguay
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=6143259&action=edit

Found Meetup application for "Asunción, Paraguay".

**Comment by courtney-pk** [comment]
Vetting for this applicant was done on a WordCamp application last month. Notes added to tracker, sent email to notify applicant of the existing group and advised them to join and offer to help organize.
