### ISSUE TITLE
[WordPress Event] Valencia, Spain

### ISSUE THREAD

**Issue by bombaypirate** [WordPress/Community-Team#74]
### Event Name:

Valencia, Spain
### Event Type:

WordPress Event
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=6159938&action=edit

Found WordCamp application for "Valencia, Spain".

**Comment by devinmaeztri** [comment]
Hello @bombaypirate, this application actually is other WordPress event application. Should it be removed from the WordCamp Application board?

**Comment by devinmaeztri** [comment]
Hello @bombaypirate and @leogopal, I think to be consistent and to avoid confusion, I will add the other WP event applications to this board for now as they come to WordCamp tracker, and add proper labels to the issue.

**Comment by lumicliment** [comment]
Although it is not a WordCamp, in HelpScout I have used the WordCamp Orientation Programming Template... changing the word "WordCamp" to "Event", and send you the link to the WordCamp orientation schedule.

**Comment by lumicliment** [comment]
z
