### ISSUE TITLE
[Meetup] London

### ISSUE THREAD

**Issue by bombaypirate** [WordPress/Community-Team#75]
### Event Name:

London
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=6158549&action=edit

Found Meetup application for "London".

**Comment by askdesign** [comment]
I have completed the vetting for this application. Please review and advise regarding next steps. Thank you!

**Comment by flopez1977** [comment]
Already added my personal notes and very good job from @askdesign

**Comment by courtney-pk** [comment]
Moving back to `In Review`, as we are awaiting feedback and guidance on next steps from Program Managers.

**Comment by courtney-pk** [comment]
Program Managers have reached a consensus to proceed with this application. @askdesign you can close this issue. Thank you!

**Comment by askdesign** [comment]
@courtney-pk I changed its Github status to "complete".
