### ISSUE TITLE
[Meetup] WordPress Latinoamérica

### ISSUE THREAD

**Issue by bombaypirate** [WordPress/Community-Team#76]
### Event Name:

WordPress Latinoamérica
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=6083043&action=edit

Found Meetup application for "WordPress Latinoamérica".

**Comment by courtney-pk** [comment]
Vetting has been completed. Notes added to tracker, and email has been sent to schedule orientation.
