### ISSUE TITLE
[Meetup] Częstochowa, Poland

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#79]
### Event Name:

Częstochowa, Poland
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=6204363&action=edit

2nd application, which we'll use to vet:
https://central.wordcamp.org/wp-admin/post.php?post=6467978&action=edit&classic-editor

Found Meetup application for "Częstochowa, Poland".

**Comment by askdesign** [comment]
Vetting completed. Needs to be reviewed by a program manager.

**Comment by courtney-pk** [comment]
Sent training and scheduling email to both applicants.
