### ISSUE TITLE
[Meetup] Kumasi, Ghana

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#80]
### Event Name:

Kumasi, Ghana
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=6137706&action=edit

Found Meetup application for "Kumasi, Ghana".

**Comment by askdesign** [comment]
I have completed the vetting for this application. Please review and advise regarding next steps. Thank you!

**Comment by devinmaeztri** [comment]
Hello @askdesign! I will send a follow-up email to invite them to schedule an orientation. Thank you so much! Do you want to close this issue? So it appears on your profile. :)

**Comment by askdesign** [comment]
Hi @devinmaeztri , Great news! Yes, I'll close this issue. thank you!
