### ISSUE TITLE
[Meetup] Barrington or Palatine

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#89]
### Event Name:

Barrington or Palatine
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=6241000&action=edit

Found Meetup application for "Barrington or Palatine".

**Comment by courtney-pk** [comment]
Vetting notes added to the tracker.

**Comment by askdesign** [comment]
Application declined, email sent.
